# Generated by Django 4.2.6 on 2023-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_text', models.TextField()),
                ('formula_photo', models.ImageField(blank=True, null=True, upload_to='formulas/media/')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
