# Generated by Django 4.2.3 on 2023-10-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_alter_formula_formula_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='formula',
            old_name='formula_text',
            new_name='text_formula',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='formula_photo',
        ),
        migrations.AddField(
            model_name='formula',
            name='photo_formula',
            field=models.ImageField(blank=True, null=True, upload_to='formulas/'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulas.category'),
        ),
    ]
