# Generated by Django 4.2.3 on 2023-10-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_category_rename_formula_text_formula_text_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formula',
            name='photo_formula',
            field=models.ImageField(upload_to='formulas/photos/'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='text_formula',
            field=models.CharField(max_length=255),
        ),
    ]
