# Generated by Django 4.2.3 on 2023-10-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_alter_formula_category_alter_formula_photo_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='photo_formula',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='text_formula',
        ),
        migrations.AddField(
            model_name='formula',
            name='formulas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formula',
            name='photo_formulas',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='formula',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formula',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulas.category'),
        ),
    ]
